[package]
name = "adventus"
version = "2024.3.1"
edition = "2021"

[dependencies]
reqwest = "0.11.27"
rand = "0.8.5"
songbird = "0.4.1"
poise = "0.6.1"
anyhow = "1.0.81"
symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5.4" }
shuttle-runtime = "0.42.0"
shuttle-secrets = "0.42.0"
shuttle-serenity = "0.42.0"
shuttle-shared-db = { version = "0.42.0", features = ["postgres", "sqlx"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-futures = "0.2.5"
config = "0.14.0"
uuid = { version = "1.8.0", features = ["v4"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
chrono = "0.4.35"
url = "2.2"

[dependencies.serenity]
version = "0.12.1"
features = [
    "cache",
    "framework",
    "standard_framework",
    "voice",
    "http",
    "rustls_backend",
]

[dependencies.sqlx]
version = "0.7.4"
default-features = false
features = [
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
]


[dependencies.tokio]
version = "1.36.0"
features = ["full", "macros", "rt-multi-thread", "signal", "sync"]
