[package]
name = "adventus"
version = "2025.02.0"
edition = "2021"

[dependencies]
# reqwest = "0.11.27"
rand = "0.8.5"
# regex = "1.10.4"
# once_cell = "1.19.0"
# songbird = "0.4.1"
poise = "0.6.1"
# symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5.4" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tokio = { version = "1.41.1", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4"] }

[dependencies.serenity]
version = "0.12.4"
# features = ["voice"]

[dependencies.sqlx]
version = "0.8.3"
default-features = false
features = ["runtime-tokio", "macros", "postgres", "migrate"]
