[package]
name = "adventus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
serenity = { features = [
    "cache",
    "framework",
    "standard_framework",
    "voice",
    "http",
    "rustls_backend",
], version = "0.12" }
songbird = "0.4"
anyhow = "1.0.66"
symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5.2" }
tokio = { features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "sync",
], version = "1" }
shuttle-runtime = "0.41.0"
shuttle-secrets = "0.41.0"
shuttle-serenity = "0.41.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-futures = "0.2"
