name: Bump CalVer Version

on: pull_request

permissions:
  contents: write

jobs:
  bump-calver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Get version from main
        run: |
          git fetch origin main --depth 1 # because default is a shallow clone and we need latest origin/main commit
          main_version=$(git show origin/main:Cargo.toml | grep '^version =' | head -n 1 | awk '{print $3}' | tr -d '"')
          echo "main_version=$main_version" >> $GITHUB_ENV

      - name: Get current PR version
        run: |
          pr_version=$(grep '^version =' Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"')
          echo "pr_version=$pr_version" >> $GITHUB_ENV

      - name: Bump version if necessary
        run: |
          year_month=$(date +'%Y.%m') # get current date parts (YYYY.MM)

          main_year_month=$(echo "${{ env.main_version }}" | cut -d'.' -f1,2)
          main_patch=$(echo "${{ env.main_version }}" | cut -d'.' -f3)

          pr_year_month=$(echo "${{ env.pr_version }}" | cut -d'.' -f1,2)
          pr_patch=$(echo "${{ env.pr_version }}" | cut -d'.' -f3)

          if [ "$main_year_month" == "$year_month" ]; then
              new_patch=$(("$main_patch" + 1))
          else
              # if it's a new month, start patch to 0
              new_patch=0
          fi

          new_version="${year_month}.${new_patch}"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Update version in Cargo.toml
        run: |
          sed -i '0,/^version = .*/{s/^version = .*/version = "'"${{ env.new_version }}"'"/}' Cargo.toml

      - name: Commit and push changes
        if: ${{ env.pr_version != env.new_version }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "Bump version to ${{ env.new_version }}"
          git push
