name: Shuttle Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          name: adventus
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          no-test: true
          secrets: "DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'"
